# --- Core ZMK ---
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000    
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000   

# --- USB (keep for flashing/debug) ---
CONFIG_ZMK_USB=y
CONFIG_USB_DEVICE_STACK=y

CONFIG_NRF_STORE_REBOOT_TYPE_GPREGRET=n
